// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_mock

import (
	"context"
	"encoding/json"
	"gophkeeper/internal/domain/record"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewRecordServicerMock creates a new instance of RecordServicerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecordServicerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecordServicerMock {
	mock := &RecordServicerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RecordServicerMock is an autogenerated mock type for the Servicer type
type RecordServicerMock struct {
	mock.Mock
}

type RecordServicerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RecordServicerMock) EXPECT() *RecordServicerMock_Expecter {
	return &RecordServicerMock_Expecter{mock: &_m.Mock}
}

// BatchCreate provides a mock function for the type RecordServicerMock
func (_mock *RecordServicerMock) BatchCreate(ctx context.Context, userID int, records []record.CreateRequest) (record.BatchCreateResponse, error) {
	ret := _mock.Called(ctx, userID, records)

	if len(ret) == 0 {
		panic("no return value specified for BatchCreate")
	}

	var r0 record.BatchCreateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []record.CreateRequest) (record.BatchCreateResponse, error)); ok {
		return returnFunc(ctx, userID, records)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []record.CreateRequest) record.BatchCreateResponse); ok {
		r0 = returnFunc(ctx, userID, records)
	} else {
		r0 = ret.Get(0).(record.BatchCreateResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, []record.CreateRequest) error); ok {
		r1 = returnFunc(ctx, userID, records)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RecordServicerMock_BatchCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCreate'
type RecordServicerMock_BatchCreate_Call struct {
	*mock.Call
}

// BatchCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - records []record.CreateRequest
func (_e *RecordServicerMock_Expecter) BatchCreate(ctx interface{}, userID interface{}, records interface{}) *RecordServicerMock_BatchCreate_Call {
	return &RecordServicerMock_BatchCreate_Call{Call: _e.mock.On("BatchCreate", ctx, userID, records)}
}

func (_c *RecordServicerMock_BatchCreate_Call) Run(run func(ctx context.Context, userID int, records []record.CreateRequest)) *RecordServicerMock_BatchCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []record.CreateRequest
		if args[2] != nil {
			arg2 = args[2].([]record.CreateRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RecordServicerMock_BatchCreate_Call) Return(batchCreateResponse record.BatchCreateResponse, err error) *RecordServicerMock_BatchCreate_Call {
	_c.Call.Return(batchCreateResponse, err)
	return _c
}

func (_c *RecordServicerMock_BatchCreate_Call) RunAndReturn(run func(ctx context.Context, userID int, records []record.CreateRequest) (record.BatchCreateResponse, error)) *RecordServicerMock_BatchCreate_Call {
	_c.Call.Return(run)
	return _c
}

// BatchUpdate provides a mock function for the type RecordServicerMock
func (_mock *RecordServicerMock) BatchUpdate(ctx context.Context, userID int, updates []record.UpdateRequest) (record.BatchUpdateResponse, error) {
	ret := _mock.Called(ctx, userID, updates)

	if len(ret) == 0 {
		panic("no return value specified for BatchUpdate")
	}

	var r0 record.BatchUpdateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []record.UpdateRequest) (record.BatchUpdateResponse, error)); ok {
		return returnFunc(ctx, userID, updates)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []record.UpdateRequest) record.BatchUpdateResponse); ok {
		r0 = returnFunc(ctx, userID, updates)
	} else {
		r0 = ret.Get(0).(record.BatchUpdateResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, []record.UpdateRequest) error); ok {
		r1 = returnFunc(ctx, userID, updates)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RecordServicerMock_BatchUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchUpdate'
type RecordServicerMock_BatchUpdate_Call struct {
	*mock.Call
}

// BatchUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - updates []record.UpdateRequest
func (_e *RecordServicerMock_Expecter) BatchUpdate(ctx interface{}, userID interface{}, updates interface{}) *RecordServicerMock_BatchUpdate_Call {
	return &RecordServicerMock_BatchUpdate_Call{Call: _e.mock.On("BatchUpdate", ctx, userID, updates)}
}

func (_c *RecordServicerMock_BatchUpdate_Call) Run(run func(ctx context.Context, userID int, updates []record.UpdateRequest)) *RecordServicerMock_BatchUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []record.UpdateRequest
		if args[2] != nil {
			arg2 = args[2].([]record.UpdateRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RecordServicerMock_BatchUpdate_Call) Return(batchUpdateResponse record.BatchUpdateResponse, err error) *RecordServicerMock_BatchUpdate_Call {
	_c.Call.Return(batchUpdateResponse, err)
	return _c
}

func (_c *RecordServicerMock_BatchUpdate_Call) RunAndReturn(run func(ctx context.Context, userID int, updates []record.UpdateRequest) (record.BatchUpdateResponse, error)) *RecordServicerMock_BatchUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type RecordServicerMock
func (_mock *RecordServicerMock) Create(ctx context.Context, userID int, typ record.RecType, encryptedData string, meta json.RawMessage) (int, error) {
	ret := _mock.Called(ctx, userID, typ, encryptedData, meta)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, record.RecType, string, json.RawMessage) (int, error)); ok {
		return returnFunc(ctx, userID, typ, encryptedData, meta)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, record.RecType, string, json.RawMessage) int); ok {
		r0 = returnFunc(ctx, userID, typ, encryptedData, meta)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, record.RecType, string, json.RawMessage) error); ok {
		r1 = returnFunc(ctx, userID, typ, encryptedData, meta)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RecordServicerMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RecordServicerMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - typ record.RecType
//   - encryptedData string
//   - meta json.RawMessage
func (_e *RecordServicerMock_Expecter) Create(ctx interface{}, userID interface{}, typ interface{}, encryptedData interface{}, meta interface{}) *RecordServicerMock_Create_Call {
	return &RecordServicerMock_Create_Call{Call: _e.mock.On("Create", ctx, userID, typ, encryptedData, meta)}
}

func (_c *RecordServicerMock_Create_Call) Run(run func(ctx context.Context, userID int, typ record.RecType, encryptedData string, meta json.RawMessage)) *RecordServicerMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 record.RecType
		if args[2] != nil {
			arg2 = args[2].(record.RecType)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 json.RawMessage
		if args[4] != nil {
			arg4 = args[4].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *RecordServicerMock_Create_Call) Return(n int, err error) *RecordServicerMock_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *RecordServicerMock_Create_Call) RunAndReturn(run func(ctx context.Context, userID int, typ record.RecType, encryptedData string, meta json.RawMessage) (int, error)) *RecordServicerMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithModels provides a mock function for the type RecordServicerMock
func (_mock *RecordServicerMock) CreateWithModels(ctx context.Context, userID int, typ record.RecType, data record.Data, meta record.MetaData, deviceID string) (int, error) {
	ret := _mock.Called(ctx, userID, typ, data, meta, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithModels")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, record.RecType, record.Data, record.MetaData, string) (int, error)); ok {
		return returnFunc(ctx, userID, typ, data, meta, deviceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, record.RecType, record.Data, record.MetaData, string) int); ok {
		r0 = returnFunc(ctx, userID, typ, data, meta, deviceID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, record.RecType, record.Data, record.MetaData, string) error); ok {
		r1 = returnFunc(ctx, userID, typ, data, meta, deviceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RecordServicerMock_CreateWithModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithModels'
type RecordServicerMock_CreateWithModels_Call struct {
	*mock.Call
}

// CreateWithModels is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - typ record.RecType
//   - data record.Data
//   - meta record.MetaData
//   - deviceID string
func (_e *RecordServicerMock_Expecter) CreateWithModels(ctx interface{}, userID interface{}, typ interface{}, data interface{}, meta interface{}, deviceID interface{}) *RecordServicerMock_CreateWithModels_Call {
	return &RecordServicerMock_CreateWithModels_Call{Call: _e.mock.On("CreateWithModels", ctx, userID, typ, data, meta, deviceID)}
}

func (_c *RecordServicerMock_CreateWithModels_Call) Run(run func(ctx context.Context, userID int, typ record.RecType, data record.Data, meta record.MetaData, deviceID string)) *RecordServicerMock_CreateWithModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 record.RecType
		if args[2] != nil {
			arg2 = args[2].(record.RecType)
		}
		var arg3 record.Data
		if args[3] != nil {
			arg3 = args[3].(record.Data)
		}
		var arg4 record.MetaData
		if args[4] != nil {
			arg4 = args[4].(record.MetaData)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *RecordServicerMock_CreateWithModels_Call) Return(n int, err error) *RecordServicerMock_CreateWithModels_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *RecordServicerMock_CreateWithModels_Call) RunAndReturn(run func(ctx context.Context, userID int, typ record.RecType, data record.Data, meta record.MetaData, deviceID string) (int, error)) *RecordServicerMock_CreateWithModels_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type RecordServicerMock
func (_mock *RecordServicerMock) Delete(ctx context.Context, userID int, recordID int) error {
	ret := _mock.Called(ctx, userID, recordID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, userID, recordID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RecordServicerMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RecordServicerMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - recordID int
func (_e *RecordServicerMock_Expecter) Delete(ctx interface{}, userID interface{}, recordID interface{}) *RecordServicerMock_Delete_Call {
	return &RecordServicerMock_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, recordID)}
}

func (_c *RecordServicerMock_Delete_Call) Run(run func(ctx context.Context, userID int, recordID int)) *RecordServicerMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RecordServicerMock_Delete_Call) Return(err error) *RecordServicerMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RecordServicerMock_Delete_Call) RunAndReturn(run func(ctx context.Context, userID int, recordID int) error) *RecordServicerMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type RecordServicerMock
func (_mock *RecordServicerMock) Find(ctx context.Context, userID int, recordID int) (*record.Record, error) {
	ret := _mock.Called(ctx, userID, recordID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *record.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*record.Record, error)); ok {
		return returnFunc(ctx, userID, recordID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *record.Record); ok {
		r0 = returnFunc(ctx, userID, recordID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*record.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, userID, recordID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RecordServicerMock_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type RecordServicerMock_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - recordID int
func (_e *RecordServicerMock_Expecter) Find(ctx interface{}, userID interface{}, recordID interface{}) *RecordServicerMock_Find_Call {
	return &RecordServicerMock_Find_Call{Call: _e.mock.On("Find", ctx, userID, recordID)}
}

func (_c *RecordServicerMock_Find_Call) Run(run func(ctx context.Context, userID int, recordID int)) *RecordServicerMock_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RecordServicerMock_Find_Call) Return(record1 *record.Record, err error) *RecordServicerMock_Find_Call {
	_c.Call.Return(record1, err)
	return _c
}

func (_c *RecordServicerMock_Find_Call) RunAndReturn(run func(ctx context.Context, userID int, recordID int) (*record.Record, error)) *RecordServicerMock_Find_Call {
	_c.Call.Return(run)
	return _c
}

// GetByType provides a mock function for the type RecordServicerMock
func (_mock *RecordServicerMock) GetByType(ctx context.Context, userID int, recordType string) ([]record.Record, error) {
	ret := _mock.Called(ctx, userID, recordType)

	if len(ret) == 0 {
		panic("no return value specified for GetByType")
	}

	var r0 []record.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) ([]record.Record, error)); ok {
		return returnFunc(ctx, userID, recordType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) []record.Record); ok {
		r0 = returnFunc(ctx, userID, recordType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]record.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, userID, recordType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RecordServicerMock_GetByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByType'
type RecordServicerMock_GetByType_Call struct {
	*mock.Call
}

// GetByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - recordType string
func (_e *RecordServicerMock_Expecter) GetByType(ctx interface{}, userID interface{}, recordType interface{}) *RecordServicerMock_GetByType_Call {
	return &RecordServicerMock_GetByType_Call{Call: _e.mock.On("GetByType", ctx, userID, recordType)}
}

func (_c *RecordServicerMock_GetByType_Call) Run(run func(ctx context.Context, userID int, recordType string)) *RecordServicerMock_GetByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RecordServicerMock_GetByType_Call) Return(records []record.Record, err error) *RecordServicerMock_GetByType_Call {
	_c.Call.Return(records, err)
	return _c
}

func (_c *RecordServicerMock_GetByType_Call) RunAndReturn(run func(ctx context.Context, userID int, recordType string) ([]record.Record, error)) *RecordServicerMock_GetByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetModifiedSince provides a mock function for the type RecordServicerMock
func (_mock *RecordServicerMock) GetModifiedSince(ctx context.Context, userID int, since time.Time) ([]record.Record, error) {
	ret := _mock.Called(ctx, userID, since)

	if len(ret) == 0 {
		panic("no return value specified for GetModifiedSince")
	}

	var r0 []record.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time) ([]record.Record, error)); ok {
		return returnFunc(ctx, userID, since)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Time) []record.Record); ok {
		r0 = returnFunc(ctx, userID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]record.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RecordServicerMock_GetModifiedSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModifiedSince'
type RecordServicerMock_GetModifiedSince_Call struct {
	*mock.Call
}

// GetModifiedSince is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - since time.Time
func (_e *RecordServicerMock_Expecter) GetModifiedSince(ctx interface{}, userID interface{}, since interface{}) *RecordServicerMock_GetModifiedSince_Call {
	return &RecordServicerMock_GetModifiedSince_Call{Call: _e.mock.On("GetModifiedSince", ctx, userID, since)}
}

func (_c *RecordServicerMock_GetModifiedSince_Call) Run(run func(ctx context.Context, userID int, since time.Time)) *RecordServicerMock_GetModifiedSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RecordServicerMock_GetModifiedSince_Call) Return(records []record.Record, err error) *RecordServicerMock_GetModifiedSince_Call {
	_c.Call.Return(records, err)
	return _c
}

func (_c *RecordServicerMock_GetModifiedSince_Call) RunAndReturn(run func(ctx context.Context, userID int, since time.Time) ([]record.Record, error)) *RecordServicerMock_GetModifiedSince_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecordWithModels provides a mock function for the type RecordServicerMock
func (_mock *RecordServicerMock) GetRecordWithModels(ctx context.Context, recordID int, userID int) (record.Data, record.MetaData, error) {
	ret := _mock.Called(ctx, recordID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRecordWithModels")
	}

	var r0 record.Data
	var r1 record.MetaData
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (record.Data, record.MetaData, error)); ok {
		return returnFunc(ctx, recordID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) record.Data); ok {
		r0 = returnFunc(ctx, recordID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(record.Data)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) record.MetaData); ok {
		r1 = returnFunc(ctx, recordID, userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(record.MetaData)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = returnFunc(ctx, recordID, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// RecordServicerMock_GetRecordWithModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecordWithModels'
type RecordServicerMock_GetRecordWithModels_Call struct {
	*mock.Call
}

// GetRecordWithModels is a helper method to define mock.On call
//   - ctx context.Context
//   - recordID int
//   - userID int
func (_e *RecordServicerMock_Expecter) GetRecordWithModels(ctx interface{}, recordID interface{}, userID interface{}) *RecordServicerMock_GetRecordWithModels_Call {
	return &RecordServicerMock_GetRecordWithModels_Call{Call: _e.mock.On("GetRecordWithModels", ctx, recordID, userID)}
}

func (_c *RecordServicerMock_GetRecordWithModels_Call) Run(run func(ctx context.Context, recordID int, userID int)) *RecordServicerMock_GetRecordWithModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RecordServicerMock_GetRecordWithModels_Call) Return(data record.Data, metaData record.MetaData, err error) *RecordServicerMock_GetRecordWithModels_Call {
	_c.Call.Return(data, metaData, err)
	return _c
}

func (_c *RecordServicerMock_GetRecordWithModels_Call) RunAndReturn(run func(ctx context.Context, recordID int, userID int) (record.Data, record.MetaData, error)) *RecordServicerMock_GetRecordWithModels_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function for the type RecordServicerMock
func (_mock *RecordServicerMock) GetStats(ctx context.Context, userID int) (record.StatsResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 record.StatsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (record.StatsResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) record.StatsResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(record.StatsResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RecordServicerMock_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type RecordServicerMock_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *RecordServicerMock_Expecter) GetStats(ctx interface{}, userID interface{}) *RecordServicerMock_GetStats_Call {
	return &RecordServicerMock_GetStats_Call{Call: _e.mock.On("GetStats", ctx, userID)}
}

func (_c *RecordServicerMock_GetStats_Call) Run(run func(ctx context.Context, userID int)) *RecordServicerMock_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RecordServicerMock_GetStats_Call) Return(statsResponse record.StatsResponse, err error) *RecordServicerMock_GetStats_Call {
	_c.Call.Return(statsResponse, err)
	return _c
}

func (_c *RecordServicerMock_GetStats_Call) RunAndReturn(run func(ctx context.Context, userID int) (record.StatsResponse, error)) *RecordServicerMock_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersions provides a mock function for the type RecordServicerMock
func (_mock *RecordServicerMock) GetVersions(ctx context.Context, userID int, recordID int) ([]record.Version, error) {
	ret := _mock.Called(ctx, userID, recordID)

	if len(ret) == 0 {
		panic("no return value specified for GetVersions")
	}

	var r0 []record.Version
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]record.Version, error)); ok {
		return returnFunc(ctx, userID, recordID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []record.Version); ok {
		r0 = returnFunc(ctx, userID, recordID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]record.Version)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, userID, recordID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RecordServicerMock_GetVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersions'
type RecordServicerMock_GetVersions_Call struct {
	*mock.Call
}

// GetVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - recordID int
func (_e *RecordServicerMock_Expecter) GetVersions(ctx interface{}, userID interface{}, recordID interface{}) *RecordServicerMock_GetVersions_Call {
	return &RecordServicerMock_GetVersions_Call{Call: _e.mock.On("GetVersions", ctx, userID, recordID)}
}

func (_c *RecordServicerMock_GetVersions_Call) Run(run func(ctx context.Context, userID int, recordID int)) *RecordServicerMock_GetVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RecordServicerMock_GetVersions_Call) Return(versions []record.Version, err error) *RecordServicerMock_GetVersions_Call {
	_c.Call.Return(versions, err)
	return _c
}

func (_c *RecordServicerMock_GetVersions_Call) RunAndReturn(run func(ctx context.Context, userID int, recordID int) ([]record.Version, error)) *RecordServicerMock_GetVersions_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type RecordServicerMock
func (_mock *RecordServicerMock) List(ctx context.Context, userID int) (record.ListResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 record.ListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (record.ListResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) record.ListResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(record.ListResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RecordServicerMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type RecordServicerMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *RecordServicerMock_Expecter) List(ctx interface{}, userID interface{}) *RecordServicerMock_List_Call {
	return &RecordServicerMock_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *RecordServicerMock_List_Call) Run(run func(ctx context.Context, userID int)) *RecordServicerMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RecordServicerMock_List_Call) Return(listResponse record.ListResponse, err error) *RecordServicerMock_List_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *RecordServicerMock_List_Call) RunAndReturn(run func(ctx context.Context, userID int) (record.ListResponse, error)) *RecordServicerMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type RecordServicerMock
func (_mock *RecordServicerMock) Search(ctx context.Context, userID int, criteria record.SearchCriteria) ([]record.Record, error) {
	ret := _mock.Called(ctx, userID, criteria)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []record.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, record.SearchCriteria) ([]record.Record, error)); ok {
		return returnFunc(ctx, userID, criteria)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, record.SearchCriteria) []record.Record); ok {
		r0 = returnFunc(ctx, userID, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]record.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, record.SearchCriteria) error); ok {
		r1 = returnFunc(ctx, userID, criteria)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RecordServicerMock_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type RecordServicerMock_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - criteria record.SearchCriteria
func (_e *RecordServicerMock_Expecter) Search(ctx interface{}, userID interface{}, criteria interface{}) *RecordServicerMock_Search_Call {
	return &RecordServicerMock_Search_Call{Call: _e.mock.On("Search", ctx, userID, criteria)}
}

func (_c *RecordServicerMock_Search_Call) Run(run func(ctx context.Context, userID int, criteria record.SearchCriteria)) *RecordServicerMock_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 record.SearchCriteria
		if args[2] != nil {
			arg2 = args[2].(record.SearchCriteria)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RecordServicerMock_Search_Call) Return(records []record.Record, err error) *RecordServicerMock_Search_Call {
	_c.Call.Return(records, err)
	return _c
}

func (_c *RecordServicerMock_Search_Call) RunAndReturn(run func(ctx context.Context, userID int, criteria record.SearchCriteria) ([]record.Record, error)) *RecordServicerMock_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type RecordServicerMock
func (_mock *RecordServicerMock) SoftDelete(ctx context.Context, userID int, recordID int) error {
	ret := _mock.Called(ctx, userID, recordID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = returnFunc(ctx, userID, recordID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RecordServicerMock_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type RecordServicerMock_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - recordID int
func (_e *RecordServicerMock_Expecter) SoftDelete(ctx interface{}, userID interface{}, recordID interface{}) *RecordServicerMock_SoftDelete_Call {
	return &RecordServicerMock_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, userID, recordID)}
}

func (_c *RecordServicerMock_SoftDelete_Call) Run(run func(ctx context.Context, userID int, recordID int)) *RecordServicerMock_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RecordServicerMock_SoftDelete_Call) Return(err error) *RecordServicerMock_SoftDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RecordServicerMock_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, userID int, recordID int) error) *RecordServicerMock_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type RecordServicerMock
func (_mock *RecordServicerMock) Update(ctx context.Context, userID int, recordID int, typ record.RecType, encryptedData string, meta json.RawMessage) error {
	ret := _mock.Called(ctx, userID, recordID, typ, encryptedData, meta)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, record.RecType, string, json.RawMessage) error); ok {
		r0 = returnFunc(ctx, userID, recordID, typ, encryptedData, meta)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RecordServicerMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RecordServicerMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - recordID int
//   - typ record.RecType
//   - encryptedData string
//   - meta json.RawMessage
func (_e *RecordServicerMock_Expecter) Update(ctx interface{}, userID interface{}, recordID interface{}, typ interface{}, encryptedData interface{}, meta interface{}) *RecordServicerMock_Update_Call {
	return &RecordServicerMock_Update_Call{Call: _e.mock.On("Update", ctx, userID, recordID, typ, encryptedData, meta)}
}

func (_c *RecordServicerMock_Update_Call) Run(run func(ctx context.Context, userID int, recordID int, typ record.RecType, encryptedData string, meta json.RawMessage)) *RecordServicerMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 record.RecType
		if args[3] != nil {
			arg3 = args[3].(record.RecType)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 json.RawMessage
		if args[5] != nil {
			arg5 = args[5].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *RecordServicerMock_Update_Call) Return(err error) *RecordServicerMock_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RecordServicerMock_Update_Call) RunAndReturn(run func(ctx context.Context, userID int, recordID int, typ record.RecType, encryptedData string, meta json.RawMessage) error) *RecordServicerMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithModels provides a mock function for the type RecordServicerMock
func (_mock *RecordServicerMock) UpdateWithModels(ctx context.Context, recordID int, userID int, data record.Data, meta record.MetaData, deviceID string) error {
	ret := _mock.Called(ctx, recordID, userID, data, meta, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithModels")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, record.Data, record.MetaData, string) error); ok {
		r0 = returnFunc(ctx, recordID, userID, data, meta, deviceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RecordServicerMock_UpdateWithModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithModels'
type RecordServicerMock_UpdateWithModels_Call struct {
	*mock.Call
}

// UpdateWithModels is a helper method to define mock.On call
//   - ctx context.Context
//   - recordID int
//   - userID int
//   - data record.Data
//   - meta record.MetaData
//   - deviceID string
func (_e *RecordServicerMock_Expecter) UpdateWithModels(ctx interface{}, recordID interface{}, userID interface{}, data interface{}, meta interface{}, deviceID interface{}) *RecordServicerMock_UpdateWithModels_Call {
	return &RecordServicerMock_UpdateWithModels_Call{Call: _e.mock.On("UpdateWithModels", ctx, recordID, userID, data, meta, deviceID)}
}

func (_c *RecordServicerMock_UpdateWithModels_Call) Run(run func(ctx context.Context, recordID int, userID int, data record.Data, meta record.MetaData, deviceID string)) *RecordServicerMock_UpdateWithModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 record.Data
		if args[3] != nil {
			arg3 = args[3].(record.Data)
		}
		var arg4 record.MetaData
		if args[4] != nil {
			arg4 = args[4].(record.MetaData)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *RecordServicerMock_UpdateWithModels_Call) Return(err error) *RecordServicerMock_UpdateWithModels_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RecordServicerMock_UpdateWithModels_Call) RunAndReturn(run func(ctx context.Context, recordID int, userID int, data record.Data, meta record.MetaData, deviceID string) error) *RecordServicerMock_UpdateWithModels_Call {
	_c.Call.Return(run)
	return _c
}
