// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"crypto/tls"
	"io"
	"mime/multipart"
	"net/url"
	"time"

	"github.com/danielgtaylor/huma/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewHumaContextMock creates a new instance of HumaContextMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHumaContextMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HumaContextMock {
	mock := &HumaContextMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HumaContextMock is an autogenerated mock type for the HumaContext type
type HumaContextMock struct {
	mock.Mock
}

type HumaContextMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HumaContextMock) EXPECT() *HumaContextMock_Expecter {
	return &HumaContextMock_Expecter{mock: &_m.Mock}
}

// AppendHeader provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) AppendHeader(name string, value string) {
	_mock.Called(name, value)
	return
}

// HumaContextMock_AppendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendHeader'
type HumaContextMock_AppendHeader_Call struct {
	*mock.Call
}

// AppendHeader is a helper method to define mock.On call
//   - name string
//   - value string
func (_e *HumaContextMock_Expecter) AppendHeader(name interface{}, value interface{}) *HumaContextMock_AppendHeader_Call {
	return &HumaContextMock_AppendHeader_Call{Call: _e.mock.On("AppendHeader", name, value)}
}

func (_c *HumaContextMock_AppendHeader_Call) Run(run func(name string, value string)) *HumaContextMock_AppendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HumaContextMock_AppendHeader_Call) Return() *HumaContextMock_AppendHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *HumaContextMock_AppendHeader_Call) RunAndReturn(run func(name string, value string)) *HumaContextMock_AppendHeader_Call {
	_c.Run(run)
	return _c
}

// BodyReader provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) BodyReader() io.Reader {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BodyReader")
	}

	var r0 io.Reader
	if returnFunc, ok := ret.Get(0).(func() io.Reader); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	return r0
}

// HumaContextMock_BodyReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BodyReader'
type HumaContextMock_BodyReader_Call struct {
	*mock.Call
}

// BodyReader is a helper method to define mock.On call
func (_e *HumaContextMock_Expecter) BodyReader() *HumaContextMock_BodyReader_Call {
	return &HumaContextMock_BodyReader_Call{Call: _e.mock.On("BodyReader")}
}

func (_c *HumaContextMock_BodyReader_Call) Run(run func()) *HumaContextMock_BodyReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HumaContextMock_BodyReader_Call) Return(reader io.Reader) *HumaContextMock_BodyReader_Call {
	_c.Call.Return(reader)
	return _c
}

func (_c *HumaContextMock_BodyReader_Call) RunAndReturn(run func() io.Reader) *HumaContextMock_BodyReader_Call {
	_c.Call.Return(run)
	return _c
}

// BodyWriter provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) BodyWriter() io.Writer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BodyWriter")
	}

	var r0 io.Writer
	if returnFunc, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	return r0
}

// HumaContextMock_BodyWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BodyWriter'
type HumaContextMock_BodyWriter_Call struct {
	*mock.Call
}

// BodyWriter is a helper method to define mock.On call
func (_e *HumaContextMock_Expecter) BodyWriter() *HumaContextMock_BodyWriter_Call {
	return &HumaContextMock_BodyWriter_Call{Call: _e.mock.On("BodyWriter")}
}

func (_c *HumaContextMock_BodyWriter_Call) Run(run func()) *HumaContextMock_BodyWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HumaContextMock_BodyWriter_Call) Return(writer io.Writer) *HumaContextMock_BodyWriter_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *HumaContextMock_BodyWriter_Call) RunAndReturn(run func() io.Writer) *HumaContextMock_BodyWriter_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// HumaContextMock_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type HumaContextMock_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *HumaContextMock_Expecter) Context() *HumaContextMock_Context_Call {
	return &HumaContextMock_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *HumaContextMock_Context_Call) Run(run func()) *HumaContextMock_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HumaContextMock_Context_Call) Return(context1 context.Context) *HumaContextMock_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *HumaContextMock_Context_Call) RunAndReturn(run func() context.Context) *HumaContextMock_Context_Call {
	_c.Call.Return(run)
	return _c
}

// EachHeader provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) EachHeader(cb func(name string, value string)) {
	_mock.Called(cb)
	return
}

// HumaContextMock_EachHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EachHeader'
type HumaContextMock_EachHeader_Call struct {
	*mock.Call
}

// EachHeader is a helper method to define mock.On call
//   - cb func(name string, value string)
func (_e *HumaContextMock_Expecter) EachHeader(cb interface{}) *HumaContextMock_EachHeader_Call {
	return &HumaContextMock_EachHeader_Call{Call: _e.mock.On("EachHeader", cb)}
}

func (_c *HumaContextMock_EachHeader_Call) Run(run func(cb func(name string, value string))) *HumaContextMock_EachHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(name string, value string)
		if args[0] != nil {
			arg0 = args[0].(func(name string, value string))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HumaContextMock_EachHeader_Call) Return() *HumaContextMock_EachHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *HumaContextMock_EachHeader_Call) RunAndReturn(run func(cb func(name string, value string))) *HumaContextMock_EachHeader_Call {
	_c.Run(run)
	return _c
}

// GetMultipartForm provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) GetMultipartForm() (*multipart.Form, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMultipartForm")
	}

	var r0 *multipart.Form
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*multipart.Form, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *multipart.Form); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*multipart.Form)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HumaContextMock_GetMultipartForm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMultipartForm'
type HumaContextMock_GetMultipartForm_Call struct {
	*mock.Call
}

// GetMultipartForm is a helper method to define mock.On call
func (_e *HumaContextMock_Expecter) GetMultipartForm() *HumaContextMock_GetMultipartForm_Call {
	return &HumaContextMock_GetMultipartForm_Call{Call: _e.mock.On("GetMultipartForm")}
}

func (_c *HumaContextMock_GetMultipartForm_Call) Run(run func()) *HumaContextMock_GetMultipartForm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HumaContextMock_GetMultipartForm_Call) Return(form *multipart.Form, err error) *HumaContextMock_GetMultipartForm_Call {
	_c.Call.Return(form, err)
	return _c
}

func (_c *HumaContextMock_GetMultipartForm_Call) RunAndReturn(run func() (*multipart.Form, error)) *HumaContextMock_GetMultipartForm_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) Header(name string) string {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// HumaContextMock_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type HumaContextMock_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
//   - name string
func (_e *HumaContextMock_Expecter) Header(name interface{}) *HumaContextMock_Header_Call {
	return &HumaContextMock_Header_Call{Call: _e.mock.On("Header", name)}
}

func (_c *HumaContextMock_Header_Call) Run(run func(name string)) *HumaContextMock_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HumaContextMock_Header_Call) Return(s string) *HumaContextMock_Header_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *HumaContextMock_Header_Call) RunAndReturn(run func(name string) string) *HumaContextMock_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Host provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) Host() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Host")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// HumaContextMock_Host_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Host'
type HumaContextMock_Host_Call struct {
	*mock.Call
}

// Host is a helper method to define mock.On call
func (_e *HumaContextMock_Expecter) Host() *HumaContextMock_Host_Call {
	return &HumaContextMock_Host_Call{Call: _e.mock.On("Host")}
}

func (_c *HumaContextMock_Host_Call) Run(run func()) *HumaContextMock_Host_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HumaContextMock_Host_Call) Return(s string) *HumaContextMock_Host_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *HumaContextMock_Host_Call) RunAndReturn(run func() string) *HumaContextMock_Host_Call {
	_c.Call.Return(run)
	return _c
}

// Method provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) Method() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Method")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// HumaContextMock_Method_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Method'
type HumaContextMock_Method_Call struct {
	*mock.Call
}

// Method is a helper method to define mock.On call
func (_e *HumaContextMock_Expecter) Method() *HumaContextMock_Method_Call {
	return &HumaContextMock_Method_Call{Call: _e.mock.On("Method")}
}

func (_c *HumaContextMock_Method_Call) Run(run func()) *HumaContextMock_Method_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HumaContextMock_Method_Call) Return(s string) *HumaContextMock_Method_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *HumaContextMock_Method_Call) RunAndReturn(run func() string) *HumaContextMock_Method_Call {
	_c.Call.Return(run)
	return _c
}

// Operation provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) Operation() *huma.Operation {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Operation")
	}

	var r0 *huma.Operation
	if returnFunc, ok := ret.Get(0).(func() *huma.Operation); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*huma.Operation)
		}
	}
	return r0
}

// HumaContextMock_Operation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Operation'
type HumaContextMock_Operation_Call struct {
	*mock.Call
}

// Operation is a helper method to define mock.On call
func (_e *HumaContextMock_Expecter) Operation() *HumaContextMock_Operation_Call {
	return &HumaContextMock_Operation_Call{Call: _e.mock.On("Operation")}
}

func (_c *HumaContextMock_Operation_Call) Run(run func()) *HumaContextMock_Operation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HumaContextMock_Operation_Call) Return(operation *huma.Operation) *HumaContextMock_Operation_Call {
	_c.Call.Return(operation)
	return _c
}

func (_c *HumaContextMock_Operation_Call) RunAndReturn(run func() *huma.Operation) *HumaContextMock_Operation_Call {
	_c.Call.Return(run)
	return _c
}

// Param provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) Param(name string) string {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Param")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// HumaContextMock_Param_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Param'
type HumaContextMock_Param_Call struct {
	*mock.Call
}

// Param is a helper method to define mock.On call
//   - name string
func (_e *HumaContextMock_Expecter) Param(name interface{}) *HumaContextMock_Param_Call {
	return &HumaContextMock_Param_Call{Call: _e.mock.On("Param", name)}
}

func (_c *HumaContextMock_Param_Call) Run(run func(name string)) *HumaContextMock_Param_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HumaContextMock_Param_Call) Return(s string) *HumaContextMock_Param_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *HumaContextMock_Param_Call) RunAndReturn(run func(name string) string) *HumaContextMock_Param_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) Query(name string) string {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// HumaContextMock_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type HumaContextMock_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - name string
func (_e *HumaContextMock_Expecter) Query(name interface{}) *HumaContextMock_Query_Call {
	return &HumaContextMock_Query_Call{Call: _e.mock.On("Query", name)}
}

func (_c *HumaContextMock_Query_Call) Run(run func(name string)) *HumaContextMock_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HumaContextMock_Query_Call) Return(s string) *HumaContextMock_Query_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *HumaContextMock_Query_Call) RunAndReturn(run func(name string) string) *HumaContextMock_Query_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteAddr provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) RemoteAddr() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteAddr")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// HumaContextMock_RemoteAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteAddr'
type HumaContextMock_RemoteAddr_Call struct {
	*mock.Call
}

// RemoteAddr is a helper method to define mock.On call
func (_e *HumaContextMock_Expecter) RemoteAddr() *HumaContextMock_RemoteAddr_Call {
	return &HumaContextMock_RemoteAddr_Call{Call: _e.mock.On("RemoteAddr")}
}

func (_c *HumaContextMock_RemoteAddr_Call) Run(run func()) *HumaContextMock_RemoteAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HumaContextMock_RemoteAddr_Call) Return(s string) *HumaContextMock_RemoteAddr_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *HumaContextMock_RemoteAddr_Call) RunAndReturn(run func() string) *HumaContextMock_RemoteAddr_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) SetHeader(name string, value string) {
	_mock.Called(name, value)
	return
}

// HumaContextMock_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type HumaContextMock_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - name string
//   - value string
func (_e *HumaContextMock_Expecter) SetHeader(name interface{}, value interface{}) *HumaContextMock_SetHeader_Call {
	return &HumaContextMock_SetHeader_Call{Call: _e.mock.On("SetHeader", name, value)}
}

func (_c *HumaContextMock_SetHeader_Call) Run(run func(name string, value string)) *HumaContextMock_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HumaContextMock_SetHeader_Call) Return() *HumaContextMock_SetHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *HumaContextMock_SetHeader_Call) RunAndReturn(run func(name string, value string)) *HumaContextMock_SetHeader_Call {
	_c.Run(run)
	return _c
}

// SetReadDeadline provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) SetReadDeadline(time1 time.Time) error {
	ret := _mock.Called(time1)

	if len(ret) == 0 {
		panic("no return value specified for SetReadDeadline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = returnFunc(time1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// HumaContextMock_SetReadDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReadDeadline'
type HumaContextMock_SetReadDeadline_Call struct {
	*mock.Call
}

// SetReadDeadline is a helper method to define mock.On call
//   - time1 time.Time
func (_e *HumaContextMock_Expecter) SetReadDeadline(time1 interface{}) *HumaContextMock_SetReadDeadline_Call {
	return &HumaContextMock_SetReadDeadline_Call{Call: _e.mock.On("SetReadDeadline", time1)}
}

func (_c *HumaContextMock_SetReadDeadline_Call) Run(run func(time1 time.Time)) *HumaContextMock_SetReadDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HumaContextMock_SetReadDeadline_Call) Return(err error) *HumaContextMock_SetReadDeadline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *HumaContextMock_SetReadDeadline_Call) RunAndReturn(run func(time1 time.Time) error) *HumaContextMock_SetReadDeadline_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatus provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) SetStatus(code int) {
	_mock.Called(code)
	return
}

// HumaContextMock_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type HumaContextMock_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - code int
func (_e *HumaContextMock_Expecter) SetStatus(code interface{}) *HumaContextMock_SetStatus_Call {
	return &HumaContextMock_SetStatus_Call{Call: _e.mock.On("SetStatus", code)}
}

func (_c *HumaContextMock_SetStatus_Call) Run(run func(code int)) *HumaContextMock_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HumaContextMock_SetStatus_Call) Return() *HumaContextMock_SetStatus_Call {
	_c.Call.Return()
	return _c
}

func (_c *HumaContextMock_SetStatus_Call) RunAndReturn(run func(code int)) *HumaContextMock_SetStatus_Call {
	_c.Run(run)
	return _c
}

// Status provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) Status() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// HumaContextMock_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type HumaContextMock_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *HumaContextMock_Expecter) Status() *HumaContextMock_Status_Call {
	return &HumaContextMock_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *HumaContextMock_Status_Call) Run(run func()) *HumaContextMock_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HumaContextMock_Status_Call) Return(n int) *HumaContextMock_Status_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *HumaContextMock_Status_Call) RunAndReturn(run func() int) *HumaContextMock_Status_Call {
	_c.Call.Return(run)
	return _c
}

// TLS provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) TLS() *tls.ConnectionState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TLS")
	}

	var r0 *tls.ConnectionState
	if returnFunc, ok := ret.Get(0).(func() *tls.ConnectionState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tls.ConnectionState)
		}
	}
	return r0
}

// HumaContextMock_TLS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TLS'
type HumaContextMock_TLS_Call struct {
	*mock.Call
}

// TLS is a helper method to define mock.On call
func (_e *HumaContextMock_Expecter) TLS() *HumaContextMock_TLS_Call {
	return &HumaContextMock_TLS_Call{Call: _e.mock.On("TLS")}
}

func (_c *HumaContextMock_TLS_Call) Run(run func()) *HumaContextMock_TLS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HumaContextMock_TLS_Call) Return(connectionState *tls.ConnectionState) *HumaContextMock_TLS_Call {
	_c.Call.Return(connectionState)
	return _c
}

func (_c *HumaContextMock_TLS_Call) RunAndReturn(run func() *tls.ConnectionState) *HumaContextMock_TLS_Call {
	_c.Call.Return(run)
	return _c
}

// URL provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) URL() url.URL {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for URL")
	}

	var r0 url.URL
	if returnFunc, ok := ret.Get(0).(func() url.URL); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(url.URL)
	}
	return r0
}

// HumaContextMock_URL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'URL'
type HumaContextMock_URL_Call struct {
	*mock.Call
}

// URL is a helper method to define mock.On call
func (_e *HumaContextMock_Expecter) URL() *HumaContextMock_URL_Call {
	return &HumaContextMock_URL_Call{Call: _e.mock.On("URL")}
}

func (_c *HumaContextMock_URL_Call) Run(run func()) *HumaContextMock_URL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HumaContextMock_URL_Call) Return(uRL url.URL) *HumaContextMock_URL_Call {
	_c.Call.Return(uRL)
	return _c
}

func (_c *HumaContextMock_URL_Call) RunAndReturn(run func() url.URL) *HumaContextMock_URL_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type HumaContextMock
func (_mock *HumaContextMock) Version() huma.ProtoVersion {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 huma.ProtoVersion
	if returnFunc, ok := ret.Get(0).(func() huma.ProtoVersion); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(huma.ProtoVersion)
	}
	return r0
}

// HumaContextMock_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type HumaContextMock_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *HumaContextMock_Expecter) Version() *HumaContextMock_Version_Call {
	return &HumaContextMock_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *HumaContextMock_Version_Call) Run(run func()) *HumaContextMock_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HumaContextMock_Version_Call) Return(protoVersion huma.ProtoVersion) *HumaContextMock_Version_Call {
	_c.Call.Return(protoVersion)
	return _c
}

func (_c *HumaContextMock_Version_Call) RunAndReturn(run func() huma.ProtoVersion) *HumaContextMock_Version_Call {
	_c.Call.Return(run)
	return _c
}
